# Generated by Django 3.1.7 on 2021-04-08 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_bank_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='bank_account',
        ),
    ]
