# Generated by Django 3.1.7 on 2021-04-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='bank_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
